idf_component_register(SRCS "common/wave.c"
                             "fft/kiss_fft.c"
                             "fft/kiss_fftr.c"
                             "ft8/constants.c"
                             "ft8/encode.c"
                             "ft8/pack.c"
                             "ft8/text.c"
                             "ft8/ldpc.c"
                             "ft8/decode.c"
                             "ft8/crc.c"
                             "ft8/unpack.c"
                       INCLUDE_DIRS "." "common" "fft" "ft8")
